name: Create PR to main with cherry-pick from release

on: 
  pull_request_target:
    branches:
      - 'main'
    types: ["closed"]
    
jobs:
  analyse-labels:
    runs-on: ubuntu-latest
    outputs:
      branches: ${{ steps.main.outputs.versions }}
    steps:
      - name: main
        id: main
        run: |
          labels='${{ toJSON(github.event.pull_request.labels.*.name) }}'
          versions=$(echo "$labels" | grep -oE '[0-9]+\.[0-9]+(\.[0-9]+)?([a-zA-Z]+[0-9]*)?')

          versions=$(jq -ncR '[inputs]' <<< "$versions")

          echo "versions=$versions" | tee -a "$GITHUB_OUTPUT" 

  cherry-pick-release-commit:
    name: Cherry-pick release commit
    runs-on: ubuntu-latest
    needs: analyse-labels
    environment: 
      name: main
    strategy:
      matrix:
        branch: ${{ fromJSON(needs.analyse-labels.outputs.branches) }}
    steps:
      
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          token: ${{ secrets.PAT }}

      - name: github-cherry-pick-action v1.0.3
        uses: carloscastrojumo/github-cherry-pick-action@bb0869df47c27be4ae4c7a2d93d22827aa5a0054
        with:
          branch: r${{ matrix.branch }}
          labels: |
            cherry-pick
          reviewers: |
            ${{ github.event.pull_request.user.login }}
        
      - name: Send Slack message on failure
        if: failure()
        run: |
          URL=https://github.com/NVIDIA/NeMo/pull/${{ github.event.number }}

          MESSAGE='{
            "blocks": [
              {
                "type": "section",
                "text": {
                  "type": "mrkdwn",
                  "text": ":alert: Cherrypick bot 🤖: Cherry-pick of <'$URL'|#'${{ github.event.number }}'> failed"
                }
              }
            ]
          }'

          curl -X POST -H "Content-type: application/json" --data "$MESSAGE" ${{ secrets.SLACK_WEBHOOK }}

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}